### ISSUE TITLE
This padding removal will cause Fragment UI to have a space at the top.

### ISSUE THREAD

**Issue by dchance1** [dchance1/healthy-find-app#10]
Need to add padding back.

This padding removal will cause Fragment UI to have a space at the top.
-Darren Chance
@leosamayoa

_Originally posted by @dchance1 in https://github.com/dchance1/healthy-find-app/pull/9#discussion_r1658616838_

**Comment by leo-valenciacollege** [comment]
Thank you for the revision @dchance1! I created a new branch for your review to see if that helps to fix the spacing issue. I will do another pull request for the "recipe-ui-updates-space-issue" branch i just pushed.
